class OperationType:
    PLUS = '+'
    MINUS = '-'
    TIMES = '*'
    DIVIDE = '/'
    AND = '&&'
    OR = '||'
    NOT = '!'
    EQUALS = '=='
    NOT_EQ = '!='
    LESS_THAN = '<'
    GREATER_THAN = '>'
    LESS_EQ = '<='
    GREATER_EQ = '>='